version: '3'

services:
  db:
    build: src/postgresql
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  backend:
    build: src/backend/transcendence/
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
    