version: '3'

services:
  db:
    build: src/db
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  backend:
    build: src/backend/
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: src/frontend
    restart: always
    ports:
      - "3000:3000"
    tty: true
