version: '3'

services:
  db:
    build: src/db
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "${WORKDIR_LOCAL}/src:/app"
