services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.13.4
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    networks:
      - tra
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5044 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  kibana:
    image: kibana:8.13.4
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    

  db:
    build: src/db
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h db -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./log/db:/var/log/postgresql
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-address: "tcp://logstash:5044"
    depends_on:
      - logstash
    

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "${WORKDIR_LOCAL}/src:/app"
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-address: "tcp://logstash:5044"
    