# expose:コンテナ間通信用のポート公開,ホストマシンには公開しない
# ports:ホストマシンに公開するポートを指定,ホストマシンからアクセス可

services:
  db:
    build: src/db
    env_file:
      - .env
    restart: always
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -h db -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"
        ]
      interval: 5s
      timeout: 2s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "${WORKDIR_LOCAL}/src:/app"
