# Use the official PostgreSQL image as the base image
FROM postgres:latest

#copy init_db.sh
COPY init_db.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init_db.sh
# Expose the PostgreSQL port
EXPOSE 5432