# Generated by Django 5.0.3 on 2024-04-13 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('participant_name', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.match')),
            ],
        ),
    ]
