#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 postgres <<EOSQL
	CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
	CREATE DATABASE $POSTGRES_DB WITH OWNER $POSTGRES_USER;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL