name: TestTranscendence

on: 
  push:
  pull_request:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    environment: transcendence_env


    steps:
      - uses: actions/checkout@v3
      - name: Set up .env file
        run: |
           echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
           echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
           echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
           echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
           echo "Current .env content:"
           cat .env
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build and start services
        run: |
               docker-compose up --build -d
      - name: Run tests
        run: |
            ls -al
            cat .env
            make p
      - name: Clean up
        if: always()
        run: |
             docker-compose down
             rm .env